source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
target :'GHZxiangmuB' do
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'MJExtension'
pod 'MJRefresh'
pod 'AFNetworking'
pod 'Masonry'
pod 'MMDrawerController'
pod 'BarrageRenderer'
pod 'GPUImage'
pod 'SDCycleScrollView'
end
