source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target :'GHZxiangmuB' do
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'MJExtension'
pod 'MJRefresh'
pod 'AFNetworking'
pod 'Masonry'
pod 'SDCycleScrollView'
pod 'NJKWebViewProgress'
pod 'BarrageRenderer'
pod 'LFLiveKit'
pod 'HyphenateSDK'

pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git'
end
